version: "2"
services:
  
  spring-config-server:
    build: spring-config-server/
    ports:
     - "8888:8888"
     
  spring-eureka-server:
    build: spring-eureka-server/
    ports:
     - "8761:8761"
    depends_on: 
      - spring-config-server     
     
  bodega-service:
    build: bodega-service/
    ports:
     - "8081-8089:8081"
    deploy:
      mode: replicated
      replicas: 3
    depends_on: 
      - spring-eureka-server
      
  compras-service:
    build: compras-service/
    ports:
     - "8081:8080"
    depends_on: 
      - spring-eureka-server
      
  ventas-service:
    build: ventas-service/
    ports:
     - "8082:8080"
    depends_on: 
      - spring-eureka-server     
     
     
 # bodega-service:
 #   build: bodega-service/
 #    command: python app.py
 #    ports:
 #    - "8888:8888"
 #   volumes:
 #    - ./web:/code # modified here to take into account the new app path
 #   links:
 #    - redis
 #   environment:
 #    - DATADOG_HOST=datadog # used by the web app to initialize the Datadog library
#  redis:
#    image: redis
#  # agent section
#  datadog:
#    build: datadog
#    links:
#     - redis # ensures that redis is a host that the container can find
#     - web # ensures that the web app can send metrics
#    environment:
#     - DD_API_KEY=__your_datadog_api_key_here__
#    volumes:
#     - /var/run/docker.sock:/var/run/docker.sock
#     - /proc/:/host/proc/:ro
#     - /sys/fs/cgroup:/host/sys/fs/cgroup:ro
