version: "3"
services:
  
  spring-config-server:
    build: spring-config-server/
    ports:
     - "8888:8888"
     
  spring-eureka-server:
    build: spring-eureka-server/
    ports:
     - "8761:8761"
    depends_on: 
      - spring-config-server     

  spring-gateway-zuul:
    build: spring-eureka-server/
    ports:
     - "8765:8765"
    depends_on: 
      - spring-config-server     

  spring-hystrix-dashboard:
    build: spring-hystrix-dashboard/
    ports:
     - "9999:9999"
    depends_on: 
      - spring-config-server     
     
  bodega-service:
    build: bodega-service/
    ports:
     - "8081-8089:8081"
    depends_on: 
      - spring-eureka-server
    deploy:
      restart_policy:
        condition: always
        max_attempts: 2
        window: 30s

  ventas-service:
    build: bodega-service/
    ports:
     - "8801-8809:8801"
    depends_on: 
      - spring-eureka-server
    deploy:
      restart_policy:
        condition: always
        max_attempts: 2
        window: 30s

  zipkin:
    image: openzipkin/zipkin
    environment:
      RABBIT_URI: "amqp:rabbit"
    ports:
     - "9411:9411"
     
  rabbit:
    image: rabbitmq:3-management
    environment:
#       RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
       RABBITMQ_DEFAULT_USER: "rabbitmq"
       RABBITMQ_DEFAULT_PASS: "rabbitmq"
       RABBITMQ_DEFAULT_VHOST: "/"
    ports:
     - "15672:15672"
     - "5672:5672"
          
#  ventas-service:
#    build: ventas-service/
#    ports:
#     - "8801-8809:8801"
#    depends_on: 
#      - spring-eureka-server
      
#  compras-service:
#    build: compras-service/
#    ports:
#     - "8082:8080"
#    depends_on: 
#      - spring-eureka-server      